// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7yA911syRDqa4VgxbIAQ2cueyMn2hC2E',
    appId: '1:946527431740:web:a448375deb2ffc5973e739',
    messagingSenderId: '946527431740',
    projectId: 'my-recipe-app-58bb3',
    authDomain: 'my-recipe-app-58bb3.firebaseapp.com',
    storageBucket: 'my-recipe-app-58bb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBesQzdTfvvTg8xYp5u4Gi_REzwjaB1Jr8',
    appId: '1:946527431740:android:b5583c6b02d6ac5473e739',
    messagingSenderId: '946527431740',
    projectId: 'my-recipe-app-58bb3',
    storageBucket: 'my-recipe-app-58bb3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7yA911syRDqa4VgxbIAQ2cueyMn2hC2E',
    appId: '1:946527431740:web:d2bc8a96c052efd973e739',
    messagingSenderId: '946527431740',
    projectId: 'my-recipe-app-58bb3',
    authDomain: 'my-recipe-app-58bb3.firebaseapp.com',
    storageBucket: 'my-recipe-app-58bb3.firebasestorage.app',
  );
}
